---
- name: Ensure firewalld is installed
  become: true
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is running and enabled
  become: true
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true

- name: Allow required firewall services
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ firewall_services }}"

- name: Allow required firewall ports
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ firewall_ports }}"
